### ISSUE TITLE
Bad Request on Login

### ISSUE THREAD

**Issue by termoyer** [netducks/Netdex#75]
Hi!
When trying to log in with my newly created and verified NetDex account, I was directed to a strange URL (but still from https://de.netdex.co/). This message appears on the destination page: 
"400 Bad Request
cloudflare".
I don't know what this is all about, but it didn't help to empty the cache or use another browser (Chrome, Firefox, Safari) or another device (Windows10, iPhone SE). A login seems impossible.

---
Hi!
Bei dem Versuch, mich mit meinem frisch erstellten und verifizierten NetDex-Konto anzumelden (Login), wurde ich an eine seltsame URL geleitet (jedoch noch von https://de.netdex.co/). Auf der Zielseite erscheint diese Meldung: 
"400 Bad Request
cloudflare".
Keine Ahnung, was das soll, aber es half weder das leeren des Caches, noch einen anderer Browser (Chrome, Firefox, Safari) oder ein anderes Gerät (Windows10, iPhone SE) zu benutzen. Ein Login scheint leider unmöglich.

**Comment by timmyrs** [comment]
Und was ist diese seltsame URL?

**Comment by termoyer** [comment]
https://de.netdex.co/%egFfDffdFsdNluR6KWVvSWEVZRsCm7B8+2zMjlMal/eCjgpsUiA5dxp5Z1vKsGiDcOdwUVJ3maszOowyTZBUyl6hT9rjd5HdAN0WhYzhr/+AaAb8TDWTlslomoOXx8fDdm/WDFvUulX6rLmB1s1DsOM1krwz4mO6NjAPhz5958pDqbWptwEHHetP/HCknZlnKOkDYj/UOcP5QxzGKx3EMzUKl++8TbNcplJsPnV8UtSICLEsTx9kI+7omV28rOZr38XkmgTEDXGgxnC3X37pjWxXsVpjACrUlfHy+7R5wvzGNbSTGn8IXlj48sNZEKvbQRwFeuuR0dcTt2ffHLz6JCrYWCFcjIV9W9XsDYg0D7bv3Icola7NDH5Za2Jq9Z8xEbUZ3TCgK+/UyGpY6U4adg9HyY5tybC/Q2CSvyfoTfi5oq2syYNpdjQF0FoezNnPZZ/h6IbckPB0Gjg9FG3HCK2MAglvHGu/XdNneMy4qwxrgw58bTH9k4Js7QJZ7lh80B0PELwXvvjSKtxYZWX+2ZpUQdo3tEyzrP60+7qHQ9YAk1OLub0bKQqKQP6HeGt+jB4+XRk2w5yOBQqnjTdkomtnb2bUXqN5g+DPLCaE5FghWjfkMQiuzfiTaRPSJxgwgeoGfivuXwMfQXXyqQwGX3RGBhKapvc9EWzkr5Bt8RM=

**Comment by timmyrs** [comment]
Also, du kannst dich egal welcher Browser, egal welches Gerät, nicht in deinen Account anmelden?
Dürfte ich deinen Account-Namen haben?

**Comment by termoyer** [comment]
Richtig. Mein Benutzername ist termoyer (ja, auch dort).

**Comment by timmyrs** [comment]
Danke, das Problem sollte jetzt behoben sein.
